server.port: 7001
server.error.include-message: always

spring.application.name: warehouse

app.eureka-server: localhost

# JWT configuration
application:
  jwt:
    jwtSecret: tNO+KhVrTj3B4q0+SEwz/NSvZq7y577jOjvY4uPgAR4=
    jwtExpirationMs: 10000000000
    jwtHeader: Authorization
    jwtHeaderStart: Bearer

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

#spring.data.mongodb:
#  host: localhost
#  port: 27017
#  database: warehouse-db

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: warehouse-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: ${MONGODB_URI}

topics:
  in: order.topic
  out: warehouse.topic
  in-error: wallet-error.topic
  out-error: warehouse-error.topic

CONSUMER_TOPIC: order.topic
PRODUCER_TOPIC: warehouse.topic

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.config.activate.on-profile: docker

server.port: 8080

app.eureka-server: eureka

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

---
spring.config.activate.on-profile: kafka
#spring.cloud.stream:
#  defaultBinder: kafka
#  kafka:
#    binder:
#      replication-factor: 1
spring.kafka.bootstrap-servers: kafka:9092
