
server.port: 7001
server.error.include-message: always

spring.application.name: wallet

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.data.mongodb:
  host: localhost
  port: 27017
  database: wallet-db

spring.cloud.function.definition: walletEventProcessor

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
#    order-out-0:
#      destination: order
#      producer:
#        required-groups: auditGroup
    warehouse-out-0:
      destination: warehouse
      producer:
        required-groups: auditGroup
    wallet-in-0:
      destination: wallet
      group: walletGroup
      consumer:
        max-attempts: 1
        backOffInitialInterval: 500000
        backOffMaxInterval: 100000
        backOffMultiplier: 2.0
  kafka:
    binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9092
    bindings:
      wallet-in-0:
        consumer:
          enableDlq: true
          dlqName: wallet-events-dlq-v1

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.config.activate.on-profile: docker

server.port: 8080

app.eureka-server: eureka

spring.data.mongodb.host: mongodb

spring.cloud.stream:
  kafka:
    binder:
      brokers: kafka

---
spring.config.activate.on-profile: streaming_partitioned

#spring.cloud.stream:
#  bindings:
#    messageProcessor-in-0:
#      consumer:
#        partitioned: true
#        instanceCount: 2

---
spring.config.activate.on-profile: streaming_instance_0

#spring.cloud.stream:
#  bindings:
#    messageProcessor-in-0:
#      consumer:
#        instanceIndex: 0

---
spring.config.activate.on-profile: streaming_instance_1
#
#spring.cloud.stream:
#  bindings:
#    messageProcessor-in-0:
#      consumer:
#        instanceIndex: 1

---
spring.config.activate.on-profile: kafka

management.health.rabbit.enabled: false
spring.cloud.stream:
  defaultBinder: kafka
  kafka:
    binder:
      replication-factor: 1
spring.kafka.bootstrap-servers: kafka:9092
