# JWT configuration
application:
  jwt:
    jwtSecret: tNO+KhVrTj3B4q0+SEwz/NSvZq7y577jOjvY4uPgAR4=
    jwtExpirationMs: 1000000
    jwtHeader: Authorization
    jwtHeaderStart: Bearer

server.port: 7000